version: 0.0
os: linux
files:
  - source: .env.deploy
    destination: /home/ec2-user/app
hooks:
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user