version: 0.2

env:
  variables:
    IMAGE_NAME: "softbank-api"
    APP_VERSION: "1.0.0"
  parameter-store:
    ECR_URI: "/softbank/api/ecr-uri"

phases:
  pre_build:
    commands:
      - set -euo pipefail
      - echo "ðŸ” Logging in to Amazon ECR..."
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" docker login --username AWS --password-stdin "$(echo $ECR_URI | cut -d'/' -f1)"

      # â–¶ï¸ íƒœê·¸ ê³„ì‚° + ë‹¤ìŒ phaseê¹Œì§€ ìœ ì§€ (BASH_ENV)
      - IMAGE_TAG=$(TZ='Asia/Seoul' date '+%Y%m%d%H%M%S')
      - FULL_IMAGE="${ECR_URI}:${APP_VERSION}-${IMAGE_TAG}"
      - echo "export IMAGE_TAG=${IMAGE_TAG}"        >> $BASH_ENV
      - echo "export FULL_IMAGE=${FULL_IMAGE}"      >> $BASH_ENV
      - echo "export ECR_URI=${ECR_URI}"            >> $BASH_ENV
      - echo "ðŸ“¦ Image will be ${FULL_IMAGE}"

  build:
    commands:
      - set -euo pipefail
      # âš ï¸ clean ì œê±°: ìºì‹œ ì‚´ë ¤ì„œ ë¹Œë“œ ë‹¨ì¶•. í…ŒìŠ¤íŠ¸ëŠ” ì—¬ì „ížˆ ì œì™¸
      - ./gradlew bootJar --no-daemon --configuration-cache --build-cache --parallel -x test
      - echo "ðŸš§ Building Docker image..."
      # í•„ìš” ì‹œ ì•„í‚¤í…ì²˜ ê³ ì • (ì˜ˆ: x86_64 ë¹Œë”ì—ì„œ ARM ì´ë¯¸ì§€ê°€ í•„ìš”í•˜ë©´ ìˆ˜ì •)
      # - docker buildx build --platform linux/amd64 -t ${IMAGE_NAME}:${IMAGE_TAG} .
      - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${FULL_IMAGE}
      - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_URI}:latest

  post_build:
    commands:
      - set -euo pipefail
      - echo "ðŸš€ Pushing Docker images to ECR..."
      - docker push ${FULL_IMAGE}
      - docker push ${ECR_URI}:latest

      - echo "ðŸ“ Creating deployment configuration..."
      - |
        cat > .env.deploy << EOF
        FULL_IMAGE=${FULL_IMAGE}
        ECR_URI=${ECR_URI}
        AWS_REGION=${AWS_DEFAULT_REGION}
        DYNAMODB_TABLE_NAME=chatapp-dev-messages
        REDIS_HOST=chatapp-dev-redis.oi0xeh.ng.0001.apn2.cache.amazonaws.com
        REDIS_PORT=6379
        EOF
      - cat .env.deploy

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - .env.deploy

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'