post_build:
  commands:
    - set -euo pipefail
    - source /codebuild/output/tmp/.exported_env
    - echo "ðŸš€ Pushing Docker images to ECR..."
    - docker push ${FULL_IMAGE}
    - docker push ${ECR_URI}:latest

    - echo "ðŸ“ Creating deployment configuration..."
    - |
      cat > .env.deploy << EOF
      FULL_IMAGE=${FULL_IMAGE}
      ECR_URI=${ECR_URI}
      AWS_REGION=${AWS_DEFAULT_REGION}
      EOF
    
    # ì• í”Œë¦¬ì¼€ì´ì…˜ìš© í™˜ê²½ë³€ìˆ˜ íŒŒì¼ ë¶„ë¦¬
    - |
      cat > .env.app << EOF
      DYNAMODB_TABLE_NAME=chatapp-dev-messages
      REDIS_HOST=chatapp-dev-redis.oi0xeh.ng.0001.apn2.cache.amazonaws.com
      REDIS_PORT=6379
      AWS_REGION=${AWS_DEFAULT_REGION}
      SPRING_DATA_REDIS_HOST=chatapp-dev-redis.oi0xeh.ng.0001.apn2.cache.amazonaws.com
      SPRING_DATA_REDIS_PORT=6379
      EOF
    - cat .env.deploy
    - cat .env.app

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - .env.deploy
    - .env.app  # ì¶”ê°€