version: 0.2

env:
  variables:
    IMAGE_NAME: "softbank-api"
    APP_VERSION: "1.0.0"
  parameter-store:
    ECR_URI: "/softbank/api/ecr-uri"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$(echo $ECR_URI | cut -d'/' -f1)"
      - IMAGE_TAG=$(TZ='Asia/Seoul' date '+%Y%m%d%H%M%S')
      - echo "Image tag will be ${IMAGE_TAG}"
      
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_URI}:${APP_VERSION}-${IMAGE_TAG}
      - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_URI}:latest
      
  post_build:
    commands:
      - echo "Pushing Docker images to ECR..."
      - docker push ${ECR_URI}:${APP_VERSION}-${IMAGE_TAG}
      - docker push ${ECR_URI}:latest

artifacts:
  files:
    - appspec.yml
    - taskdef.json
  discard-paths: yes
  base-directory: .